[connections.my_database]
    type="sql"
    dialect="postgresql"
    source_id="gold-braid-431812-g7"
    host="34.41.36.17" 
    port=5432
    database="myntra_roi"
    username="90northbrands"
    password="90northbrands"
    
